[theme]
base = "light"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#fafafa"
textColor = "#18181b"
primaryColor = "#3b1ee0"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
